import = [
  "~/.config/alacritty/onedark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
family = "ComicMono Nerd Font"
style = "Bold"

[font.italic]
family = "ComicMono Nerd Font"
style = "Regular"

[font.normal]
family = "ComicMono Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
decorations = "None"
