env:
  TERM: "xterm-256color"

window:
  startup_mode: Fullscreen

font:
  size: 16
  normal:
    family: "ComicMono Nerd Font"
    style: "Regular"
  italic:
    family: "ComicMono Nerd Font"
    style: "Regular"
  bold:
    family: "ComicMono Nerd Font"
    style: "Bold"
