[zsh]
path = "/home/linuxbrew/.linuxbrew/bin/zsh"
setup = "cat $HOME/.config/zsh/init.zsh"
[zsh.repos]
zinit = ".local/share/zinit"

[tmux]
[tmux.repos]
tpm = ".tmux/plugins/tpm"

[alacritty]
font_size = 20

[brew]
# path=/opt/homebrew/bin/brew for M1 mac
path = "/home/linuxbrew/.linuxbrew/bin/brew"
setup = "/home/linuxbrew/.linuxbrew/bin/brew shellenv"

[fzf]
init = "eval $(fzf --zsh)"

[oh-my-posh]
init = "eval $(oh-my-posh init zsh -c $HOME/.config/oh-my-posh/config.toml)"

[zoxide]
init = "eval $(zoxide init --cmd cd zsh)"

[zvm]
init = "source $HOME/.config/zvm/init.zsh"

[nvim]
